/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BhvrRouteImport } from './routes/bhvr'
import { Route as IndexRouteImport } from './routes/index'

const BhvrRoute = BhvrRouteImport.update({
  id: '/bhvr',
  path: '/bhvr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bhvr': typeof BhvrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bhvr': typeof BhvrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bhvr': typeof BhvrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bhvr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bhvr'
  id: '__root__' | '/' | '/bhvr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BhvrRoute: typeof BhvrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bhvr': {
      id: '/bhvr'
      path: '/bhvr'
      fullPath: '/bhvr'
      preLoaderRoute: typeof BhvrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BhvrRoute: BhvrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
